export const RecentVisitDummy = [
  {
    id: 1,
    date: "2025-10-08",
    time: "10:30 AM",
    department: "Cardiology",
    doctor: "Dr. A. Rahman",
    reason: "Chest pain checkup",
    status: "Completed",
  },
  {
    id: 2,
    date: "2025-10-06",
    time: "2:15 PM",
    department: "Neurology",
    doctor: "Dr. M. Ahsan",
    reason: "Migraine follow-up",
    status: "Pending",
  },
  {
    id: 3,
    date: "2025-10-04",
    time: "11:00 AM",
    department: "Orthopedics",
    doctor: "Dr. K. Hossain",
    reason: "Knee joint pain",
    status: "Cancelled",
  },
  {
    id: 4,
    date: "2025-10-01",
    time: "9:45 AM",
    department: "Dermatology",
    doctor: "Dr. S. Chowdhury",
    reason: "Skin allergy",
    status: "Completed",
  },
  {
    id: 5,
    date: "2025-09-29",
    time: "4:30 PM",
    department: "ENT",
    doctor: "Dr. L. Ahmed",
    reason: "Ear infection",
    status: "Completed",
  },
];